version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./builds/node.Dockerfile
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./src:/usr/app
      - node_modules:/usr/data

volumes:
  node_modules: